# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Category')),
                ('mark', models.CharField(max_length=100)),
                ('link_to_metal', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('catalog.category',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('h1', models.CharField(blank=True, max_length=100, null=True)),
                ('_menu_title', models.CharField(blank=True, max_length=30, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('_date_published', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Product')),
                ('is_new_price', models.NullBooleanField()),
                ('date_price_updated', models.DateField(blank=True, null=True)),
                ('nomen', models.BigIntegerField(blank=True, null=True)),
                ('introtext', models.TextField(blank=True, null=True)),
                ('mark', models.CharField(max_length=100)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('diameter_out', models.IntegerField(blank=True, null=True)),
                ('diameter_in', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('h1', models.CharField(blank=True, max_length=100, null=True)),
                ('_menu_title', models.CharField(blank=True, max_length=30, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('_date_published', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='object',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stroyprombeton.Territory'),
        ),
    ]
