# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-09 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0006_remove_redundant_fields'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('specification', models.TextField(blank=True, default='')),
                ('link_to_metal', models.URLField(blank=True, default='')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stroyprombeton_category', to='pages.Page')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stroyprombeton.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.Order')),
                ('company', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
            ],
            bases=('ecommerce.order',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('price', models.FloatField(blank=True, db_index=True, null=True)),
                ('in_stock', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('is_new_price', models.NullBooleanField()),
                ('date_price_updated', models.DateField(auto_now_add=True)),
                ('code', models.BigIntegerField(blank=True, null=True)),
                ('mark', models.CharField(blank=True, default='', max_length=500)),
                ('specification', models.TextField(blank=True, default='')),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('diameter_out', models.IntegerField(blank=True, null=True)),
                ('diameter_in', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stroyprombeton.Category')),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stroyprombeton_product', to='pages.Page')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
            ],
            options={
                'proxy': True,
                'abstract': False,
            },
            bases=('pages.modelpage',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
            ],
            options={
                'proxy': True,
                'abstract': False,
            },
            bases=('pages.modelpage',),
        ),
    ]
