# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-29 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroyprombeton', '0002_delete_region'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
