# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-21 09:45
from __future__ import unicode_literals

from django.db import migrations


def zero_code_to_none(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    product = (apps.get_model('stroyprombeton', 'product')
        ._default_manager.using(db_alias).filter(code=0))
    product.update(code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('stroyprombeton', '0003_auto_20161229_0848'),
    ]

    operations = [
        migrations.RunPython(zero_code_to_none),
    ]
