# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20170317_1457'),
        ('stroyprombeton', '0005_alter_catalog_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedbacksForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Client feedbacks',
                'verbose_name_plural': 'Client feedbacks',
                'proxy': True,
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='NewsForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'proxy': True,
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='RegionsForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Regions',
                'verbose_name_plural': 'Regions',
                'proxy': True,
            },
            bases=('pages.page',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorypage',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productpage',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stroyprombeton.Category', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='category',
            name='specification',
            field=models.TextField(blank=True, default='', verbose_name='specification'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(max_length=255, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stroyprombeton.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_price_updated',
            field=models.DateField(auto_now_add=True, verbose_name='date price updated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter_in',
            field=models.IntegerField(blank=True, null=True, verbose_name='diameter in'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter_out',
            field=models.IntegerField(blank=True, null=True, verbose_name='diameter out'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_price',
            field=models.NullBooleanField(verbose_name='is new price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is popular'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, db_index=True, default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, default='', verbose_name='specification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='width'),
        ),
    ]
