# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroyprombeton', '0006_auto_20170317_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='link_to_metal',
        ),
    ]
