# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stroyprombeton', '0010_update_robots_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('position', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name='position')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('position', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name='position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='stroyprombeton.TagGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'group')},
        ),
    ]
