# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroyprombeton', '0013_buff_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'group'), ('slug', 'group')]),
        ),
    ]
