# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-21 06:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroyprombeton', '0014_tag_slug_and_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_price_updated', models.DateField(auto_now_add=True, verbose_name='date price updated')),
                ('code', models.BigIntegerField(blank=True, null=True, verbose_name='code')),
                ('mark', models.CharField(blank=True, default='', max_length=500, verbose_name='mark')),
                ('specification', models.TextField(blank=True, default='', verbose_name='specification')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='length')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='height')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='volume')),
                ('diameter_out', models.IntegerField(blank=True, null=True, verbose_name='diameter out')),
                ('diameter_in', models.IntegerField(blank=True, null=True, verbose_name='diameter in')),
                ('is_new_price', models.NullBooleanField(verbose_name='is new price')),
                ('price', models.FloatField(blank=True, db_index=True, default=0, verbose_name='price')),
                ('in_stock', models.PositiveIntegerField(db_index=True, default=0, verbose_name='in stock')),
                ('is_popular', models.BooleanField(db_index=True, default=False, verbose_name='is popular')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='options', to='stroyprombeton.Tag', verbose_name='tags')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='stroyprombeton.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='stroyprombeton.Option', verbose_name='option'),
        ),
    ]
