# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 23:49
from __future__ import unicode_literals

from django.db import migrations

from catalog.models_operations import index_alphanumeric_tag_name


class Migration(migrations.Migration):

    dependencies = [
        ('stroyprombeton', '0016_reverse_option_relation'),
    ]

    operations = [
        index_alphanumeric_tag_name
    ]
