# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroyprombeton', '0021_cleanup_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_popular',
        ),
    ]
