# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 05:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_page_template_increase_name_size'),
        ('stroyprombeton', '0025_series_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000, unique=True, verbose_name='name')),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stroyprombeton_section', to='pages.Page')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='SeriesPage',
            fields=[
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'series',
                'abstract': False,
                'proxy': True,
                'indexes': [],
            },
            bases=('pages.modelpage',),
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stroyprombeton.Section', verbose_name='section'),
        ),
    ]
